In [1]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

iris_data = iris.data
iris_label = iris.target

iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

iris_df['label'] = iris.target

In [3]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [8]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_X = iris.data
iris_y = iris.target

iris_df = pd.DataFrame(iris_X, columns = iris.feature_names)
iris_df["species"] = iris_y

iris_df.tail(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
145        2  
146        2  
147        2  
148        2  
149        2

In [10]:
type(iris)

sklearn.utils._bunch.Bunch

In [11]:
from sklearn.model_selection import train_test_split

데이터 전처리

데이터 세트 분리

모델 학습 및 검증 평가

예측 수행

예측 평가

In [13]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from 

In [14]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 범주형 데이터
fruits = ['사과', '바나나', '오렌지', '바나나']

# OneHotEncoder 객체 생성
encoder = OneHotEncoder(sparse=False)

# 범주형 데이터를 숫자로 인코딩
fruits_encoded = np.array(fruits).reshape(-1, 1)
encoded_data = encoder.fit_transform(fruits_encoded)

# 인코딩된 데이터 출력
print("인코딩된 데이터:")
print(encoded_data)

인코딩된 데이터:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [15]:
import numpy as np

array = np.array([1,2,2,3,3,3,4,4,4,4])

unique_values, counts = np.unique(array, return_counts=True)

for value, count in zip(unique_values, counts):
    print(f"Value {value} appears {count} times")

Value 1 appears 1 times
Value 2 appears 2 times
Value 3 appears 3 times
Value 4 appears 4 times
